language: node_js

node_js:
  - 5

cache:
  directories:
    - node_modules

before_install:
  - "npm --version"
  - "phantomjs --version"

install:
  - "npm install"

before_script:
  - ./node_modules/.bin/http-server . &  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc


branches:
  only:
    - master