language: node_js

node_js:
  - 5

cache:
  directories:
    - node_modules

before_install:
  - "npm --version"
  - "phantomjs --version"

install:
  - "npm install"

before_script:
  - "npm run webserver"


branches:
  only:
    - master